= Data definition guide

== General

This guide provides comprehensive documentation for defining HAL resources,
setting up model registers, and configuring API endpoints. This is the
foundation phase where you establish the structure and relationships of your
HAL API client.

Before starting this guide, complete the
link:getting-started-guide.adoc[Getting started guide] to understand basic
concepts.

== Overview

=== General

HAL resources need to be defined as models to allow data access and
serialization. The data definition phase involves several key steps:

. Define HAL resource models
. Define the base API URL using the `Client` class
. Create a `ModelRegister` to manage the resource models
. Define the resource models' respective endpoints on the base API URL

== Creating a HAL model register

=== General

The `ModelRegister` class is used to manage the resource models and their
respective endpoints on the base API URL.

It relies on the `Client` class to perform HTTP requests to the API. The base
API URL is defined at the `Client` object.

NOTE: The base API URL is used for all requests made by the `Client` class,
including the requests made by the `ModelRegister` class.

[example]
====
[source,ruby]
----
require 'lutaml-hal'

# Create a new client with API endpoint
client = Lutaml::Hal::Client.new(api_url: 'https://api.example.com')
register = Lutaml::Hal::ModelRegister.new(name: :my_model_register, client: client)
# Or set client later, `register.client = client`
----
====

The `name:` parameter is used to identify the `ModelRegister` instance.

== Creating a HAL global register

=== General

The `GlobalRegister` class is a singleton that manages one or more
`ModelRegister` instances.

It is optional, but is required for automatic realization of models from Link
objects. See the link:runtime-usage-guide.adoc[Runtime usage guide] for more
details on fetching resources via link realization.

[example]
====
[source,ruby]
----
require 'lutaml-hal'

# Create a new client with API endpoint
client = Lutaml::Hal::Client.new(api_url: 'https://api.example.com')
register = Lutaml::Hal::ModelRegister.new(name: :my_model_register, client: client)

# Register the ModelRegister with the global register
global_register = Lutaml::Hal::GlobalRegister.instance.register(:my_model_register, register)

# Obtain the global register
global_register.get(:my_model_register)

# Delete a register mapping
global_register.delete(:my_model_register)
----
====

== Defining HAL resource models

=== General

A HAL resource is defined by creating a subclass of the `Resource` class and
defining its attributes, links, and key-value mappings.

The `Resource` class is the base class for defining HAL resource models. It
inherits from `Lutaml::Model::Serializable`, which provides data modelling and
serialization capabilities.

The declaration of attributes, links, and key-value mappings for a HAL resource
is performed using the `attribute`, `hal_link`, and `key_value` methods.

There are 3 levels of data modeling in a HAL resource, all of which are
necessary for the full usage of a HAL resource:

* Resource attributes
* Serialization mappings
* HAL Links

=== Integrated example of a resource model

[example]
====
[source,ruby]
----
module MyApi
  class Product < Lutaml::Hal::Resource
    attribute :id, :string
    attribute :name, :string
    attribute :price, :float

    hal_link :self, key: 'self', realize_class: 'Product'
    hal_link :category, key: 'category', realize_class: 'Category'

    key_value do
      map 'id', to: :id
      map 'name', to: :name
      map 'price', to: :price
    end
  end
end
----
====

=== Resource attributes

==== General

A resource attribute is a direct property of the HAL resource.

These attributes typically hold values of simple data types, and are directly
serialized into JSON.

These attributes are declared using the `attribute` method from `lutaml-model`.

[example]
====
A HAL resource of class `Product` can have attributes `id`, `name`, and `price`.
====

Please refer to syntax as described in the
https://github.com/lutaml/lutaml-model[`lutaml-model`] documentation.

==== Example of a resource model with attributes

[example]
====
[source,ruby]
----
module MyApi
  class Product < Lutaml::Hal::Resource
    attribute :id, :string
    attribute :name, :string
    attribute :price, :float
    # ...
  end
end
----
====

=== Serialization mapping of resource attributes

==== General

A serialization mapping defines rules to serialize a HAL resource to and from a
serialization format. In HAL, the serialization format is JSON, but other
formats can also be supported.

The mapping between the HAL model attributes and their corresponding JSON
serialization is performed using the `key_value do` or `json do` blocks from
`lutaml-model`. The mapping of the contents of `_links` is automatically
performed using `hal_link`.

[example]
====
A HAL resource of class `Product` with attributes `id`, `name`, and `price`
will need to declare a `key_value` block to map the attributes to their
corresponding JSON keys, namely, `"id"`, `"name"`, and `"price"`.
====

Please refer to syntax as described in the
https://github.com/lutaml/lutaml-model[`lutaml-model`] documentation.

==== Example of a resource model with serialization mapping

[example]
====
[source,ruby]
----
module MyApi
  class Product < Lutaml::Hal::Resource
    attribute :id, :string
    attribute :name, :string
    attribute :price, :float

    key_value do
      map 'id', to: :id
      map 'name', to: :name
      map 'price', to: :price
    end
  end
end
----
====

=== HAL Links

==== General

A HAL resource has links to other resources, typically serialized in the
`_links` section of the JSON response.

[example]
====
A HAL resource of class `Product` can have links `self` (which is a
self-referential identifier link) and `category`.
====

HAL links need to be defined in the resource model to allow the resolution of
the links to their target resources.

These links are declared using the `hal_link` method provided by `lutaml-hal`.

==== Syntax

[source,ruby]
----
hal_link :link_name,
  key: 'link_key',
  realize_class: 'TargetResourceClass',
  link_class: 'LinkClass',
  link_set_class: 'LinkSetClass'
----

Where:

`:link_name`:: The name of the link, which will be used to access the link in
the resource object.

`key: 'link_key'`:: The key of the link in the JSON response. This is the name
of the link as it appears in the `_links` section of the HAL resource.

`realize_class: 'TargetResourceClass'`:: The class of the target resource that
the link points to. This is used to resolve the link to the associated
resource.
+
The `realize_class` parameter supports two distinct use cases:
+
--
**String reference (recommended)**: Use string class names to delay resolution,
especially when classes may be dynamically loaded or not available at
definition time:

[source,ruby]
----
hal_link :category, key: 'category', realize_class: 'Category'
hal_link :products, key: 'products', realize_class: 'ProductIndex'
----

**Class reference**: Use actual class objects when classes are statically
available at definition time or via autoload:

[source,ruby]
----
hal_link :category, key: 'category', realize_class: Category
hal_link :products, key: 'products', realize_class: ProductIndex
----

The framework's lazy resolution mechanism handles both cases seamlessly,
automatically resolving string references to actual classes when needed during
serialization. This ensures consistent type names in HAL output regardless of
class loading order.
--

`link_class: 'LinkClass'`:: (optional) The class of the link that defines
specific behavior or attributes for the link object itself. This is
dynamically created and is inherited from `Lutaml::Hal::Link` if not provided.
+
Like `realize_class`, this parameter supports both string and class references:
+
--
**String references (Recommended)**: Use string class names for maximum
flexibility:

[source,ruby]
----
hal_link :category, key: 'category', realize_class: 'Category', link_class: 'CategoryLink'
----

**Class references**: Use actual class objects when classes are statically
available:

[source,ruby]
----
hal_link :category, key: 'category', realize_class: Category, link_class: CategoryLink
----
--

`link_set_class: 'LinkSetClass'`:: (optional) The class of the link set object
that contains the links. This is dynamically created and is inherited from
`Lutaml::Hal::LinkSet` if not provided.
+
Like `realize_class`, this parameter supports both string and class references:
+
--
**String references (Recommended)**: Use string class names for maximum
flexibility:

[source,ruby]
----
hal_link :category, key: 'category', realize_class: 'Category', link_set_class: 'ProductLinkSet'
----

**Class references**: Use actual class objects when classes are statically
available:

[source,ruby]
----
hal_link :category, key: 'category', realize_class: Category, link_set_class: ProductLinkSet
----
--

==== Integrated example of a HAL resource model using auto-generated LinkSet and Link classes

[example]
====
For an instance of `Product`:

[source,ruby]
----
module MyApi
  class Product < Lutaml::Hal::Resource
    attribute :id, :string
    attribute :name, :string
    attribute :price, :float

    hal_link :self, key: 'self', realize_class: 'Product'
    hal_link :category, key: 'category', realize_class: 'Category'

    key_value do
      map 'id', to: :id
      map 'name', to: :name
      map 'price', to: :price
    end
  end
end
----

The library will provide:

* the link set (serialized in HAL as JSON `_links`) in the class
  `ProductLinkSet`.

* the link set contains the `self` link (as `ProductLink`) and the `category`
  link (as `CategoryLink`).

As a result:

* calling `product.links.self` will return an instance of `ProductLink`.

* calling `product.links.self.realize(register)` will dynamically fetch and
  return an instance of `Product`.
====

==== Dynamic definition of LinkSet and Link

===== General

The `_links` section is modeled as a dynamically created link set class, named
after the resource's class name (with an appended `LinkSet` string), which in
turn contains the defined links to other resources. The link set class is
automatically inherited from `Lutaml::Hal::LinkSet`.

Each link in the link set is modeled as a dynamically created link class,
named after the resource's class name (with an appended `Link` string). This
link class is inherited from `Lutaml::Hal::Link`.

[example]
====
A HAL resource of class `Product` may have a link set of class
`ProductLinkSet` which contains the `self` and `category` links as its
attributes.
====

The framework automatically:

* Creates the LinkSet class when the resource class is defined
* Adds a `links` attribute to the resource class
* Maps the `_links` JSON key to the `links` attribute
* Ensures consistent type naming regardless of class loading order

Each link object of the link set is provided as a `Link` object that is
dynamically created for the type of resolved resource. The name of the link
class is the same as the resource class name with an appended `Link` string.
This Link class is inherited from `Lutaml::Hal::Link`.

[example]
====
A HAL resource of class `Product` with a link set that contains the `self`
(points to a `Product`) and `category` (points to a `Category`) links will
have:

* a link set of class `ProductLinkSet` which contains:
** a `self` attribute that is an instance of `ProductLink`
** a `category` attribute that is an instance of `CategoryLink`
====

==== Lazy realization class loading and type naming

===== General

The framework implements lazy type resolution of the `realize_class` argument
in the `hal_link` command. This allows the instance to be realized on
resolution to have its class defined after the definition of the `hal_link`
command, for example, in the case when the class to be realized is loaded
later in the application lifecycle.

Technically, it is possible to have all models (the classes to be realized) to
be defined before the HAL resource is created to ensure the realization
classes are resolved. However, there are cases where classes are dynamically
generated, resolved via registers or other mechanisms that make those classes
available after the HAL resource is defined.

This allows for greater flexibility in defining resource relationships and
enables the use of dynamic class loading techniques.

In addition, the definition of the `realize_class` argument in the `hal_link`
command becomes useful in the case of polymorphism. The type name is used in
Lutaml::Model for polymorphism and potentially serialized (if defined through
Lutaml::Model serializatiion methods, as a Hal::Resource is also a
Lutaml::Model).

NOTE: This framework uses base class names (e.g., `ResourceClass`) instead of
fully qualified namespaced class names (e.g., `MyModule::ResourceClass`) as
the `type` attribute, by default.

==== Custom link set class

===== General

When a custom link set class (via `link_set_class:`) is provided, links are no
longer automatically added to the link set via `hal_link`. Please ensure that
all links are defined as model `attributes` and their `key_value` mappings
provided.

This is useful for the scenario where the link set needs to be customized to
provide additional attributes or behavior.

A LinkSetClass for a resource must implement the following interface:

[source,ruby]
----
module MyApi
  # This represents the link set of a Resource
  class ResourceLinkSet < Lutaml::Model::Serializable
    attribute :attribute_name_1, :link_class_1, collection: {true|false}
    attribute :attribute_name_2, :link_class_2, collection: {true|false}
    # ...

    key_value do
      map 'link_key_1', to: :attribute_name_1
      map 'link_key_2', to: :attribute_name_2
      # ...
    end
  end

  # This represents the basic setup of a Resource with a custom LinkSet class
  class Resource < Lutaml::Hal::Resource
    attribute :links, ResourceLinkSet
    # Define resource attributes

    key_value do
      # This is the mapping of the `_links` key to the attribute `links`.
      map '_links', to: :links
      # Mappings for resource attributes need to be explicitly provided
    end
  end
end
----

Alternatively, it is possible to re-open the dynamically created link set
class and add additional attributes to it.

===== Override the default link set class for Product

[source,ruby]
----
module MyApi
  class Product < Lutaml::Hal::Resource
    attribute :id, :string
  end
  # The class `MyApi::ProductLinkSet` is created automatically by the library.

  # Re-open the default link set class and add additional attributes
  class ProductLinkSet < Lutaml::Hal::LinkSet
    # Add additional attributes to the link set
    attribute :custom_link_set_attribute, Something, collection: false

    key_value do
      map 'my_custom_link', to: :custom_link_set_attribute
    end
  end
end
----

==== Custom link class

===== General

When a custom link class (via `link_class:`) is provided, the custom link
class is automatically added into the link set.

This makes it possible to:

* supplement the link with additional attributes, or
* override the `realize(register)` method to provide custom behavior for the
  link.

A Link class pointing to a resource must implement the following interface:

[source,ruby]
----
module MyApi
  # This represents a link set pointing to a Resource
  class TargetResourceLink < Lutaml::Model::Serializable
    # This is the link class for the resource class Resource
    # 'default:' needs to be set to the name of the target resource class
    attribute :type, :string, default: 'Resource'

    # No specification of key_value block needed since attribute presence
    # provides a default mapping.
  end
end
----

Alternatively, it is possible to re-open the dynamically created link class
and add additional attributes to it.

===== Override the default link class for Product

[source,ruby]
----
module MyApi
  class Product < Lutaml::Hal::Resource
    attribute :id, :string
    hal_link :category, key: 'category', realize_class: 'Category'
  end
  # The class `MyApi::CategoryLink` is created automatically by the library.

  # Re-open the default link class and add additional attributes
  class CategoryLink < Lutaml::Hal::Link
    # Add additional attributes to the link
    attribute :language_code, :string, collection: false

    key_value do
      map 'language_code', to: :language_code
    end
  end
end
----

== Registering resource models and endpoints

=== General

The `ModelRegister` allows you to register resource models and their
endpoints.

You can define endpoints for collections (index) and individual resources
(resource) using the `add_endpoint` method.

=== The add_endpoint method

The `add_endpoint` method takes the following parameters:

`id`:: A unique identifier for the endpoint.

`type`:: The type of endpoint, which can be `index` or `resource`.

`url`:: The URL of the endpoint, which can include path parameters.
+
In the `url`, you can use interpolation parameters, which will be replaced
with the actual values when fetching the resource. The interpolation
parameters are defined in the `url` string using curly braces `{}`.

`model`:: The class of the resource that will be fetched from the API. The
class must inherit from `Lutaml::Hal::Resource`.

`parameters`:: (optional) An array of `Lutaml::Hal::EndpointParameter` objects
defining query parameters that should be appended to the URL when fetching the
resource. Each parameter includes schema validation and documentation.
+
This is essential for APIs that require query parameters for pagination,
filtering, or other functionality where the same base URL needs different
query parameters to access different resources or views.

`embed_config`:: (optional) Configuration for HAL embed support. This allows
the endpoint to fetch resources with embedded content, reducing the number of
HTTP requests needed. See the <<embed-configuration,Embed configuration>>
section for details.

The `add_endpoint` method will automatically handle the URL resolution and
fetch the resource from the API.

When the `ModelRegister` fetches a resource using the `realize` method, it
will match the resource URL against registered paths in order to find the
appropriate model class to use for deserialization and resolution.

=== Syntax

[source,ruby]
----
register.add_endpoint( <1>
  id: :model_index, <2>
  type: :index, <3>
  url: '/url_supporting_interpolation/{param}', <4>
  model: ModelClass <5>
)
----
<1> The `add_endpoint` method is used to register an endpoint for a model.
<2> The `id` is a unique identifier for the endpoint, which is required to
    fetch the resource later.
<3> The `type` specifies the type of endpoint, which can be `index` or
    `resource`. The `index` type is used for collections, while the
    `resource` type is used for individual resources.
<4> The `url` is the URL of the endpoint, which can include path parameters.
    The URL can also include interpolation parameters, which will be replaced
    with the actual values when fetching the resource.
<5> The `model` is the class of the resource that will be fetched from the
    API. The class must inherit from `Lutaml::Hal::Resource`.

=== Example of registering and using query parameters

[example]
====
[source,ruby]
----
# Register an endpoint that supports pagination via query parameters
register.add_endpoint(
  id: :product_index,
  type: :index,
  url: '/products',
  model: ProductIndex,
  parameters: [
    Lutaml::Hal::EndpointParameter.query('page',
      schema: { type: :integer },
      description: 'Page number'
    ),
    Lutaml::Hal::EndpointParameter.query('items',
      schema: { type: :integer },
      description: 'Items per page'
    )
  ]
)

# Fetch the first page with 10 items per page
page_1 = register.fetch(:product_index, page: 1, items: 10)
# => client.get('/products?page=1&items=10')

# Fetch the second page with 5 items per page
page_2 = register.fetch(:product_index, page: 2, items: 5)
# => client.get('/products?page=2&items=5')
----
====

=== Example of registering the Product class to both index and resource endpoints

[example]
====
[source,ruby]
----
register.add_endpoint(
  id: :product_index,
  type: :index,
  url: '/products',
  model: Product
)

register.add_endpoint(
  id: :product_resource,
  type: :resource,
  url: '/products/{id}',
  model: Product
)
----
====

For advanced path pattern examples, see
link:complex-path-patterns.adoc[Complex path pattern examples].

== Defining HAL page models

=== General

HAL index APIs often support pagination, which allows clients to retrieve a
limited number of resources at a time.

The `Lutaml::Hal::Page` class is used to handle pagination in HAL APIs. It is
a subclass of `Resource`, and provides additional attributes and methods for
handling pagination information

=== Default page attributes

The `Page` class by default supports the following attributes:

`page`:: The current page number.
`pages`:: The total number of pages.
`limit`:: The number of resources per page.
`total`:: The total number of resources.

=== Page usage pattern

The way to use the `Page` class is through inheritance from it, where the
class will automatically create the necessary links for typical page objects.

The typical links of a page object are:

`self`:: A link to the current page.
`prev`:: A link to the previous page.
`next`:: A link to the next page.
`first`:: A link to the first page.
`last`:: A link to the last page.

The "realize class" of these links are the same as the inherited page object,
ensuring consistency in the pagination model.

=== Syntax

[source,ruby]
----
class ProductIndex < Lutaml::Hal::Page
  # No attributes necessary
end

register.add_endpoint(
  id: :product_index,
  type: :index,
  url: '/products',
  model: ProductIndex
)

page_1 = register.fetch(:product_index)
page_2_link = page_1.links.next
# => <#ProductIndexLink href: "/products/2", title: "Next Page">
----

Where:

`ProductIndex`:: The class of the page that will be fetched from the API. The
class must inherit from `Lutaml::Hal::Page`.
`register`:: The instance of `ModelRegister`.
`id`:: The ID of the pagination endpoint to be registered in the
`ModelRegister`.
`url`:: The URL of the pagination endpoint.
`model`:: The class of the page that will be fetched from the API.

[[embed-configuration]]
== Embed configuration

=== General

HAL embed support allows endpoints to fetch resources with embedded content,
significantly reducing the number of HTTP requests needed to access related
data. This is particularly useful for APIs that support HAL's `_embedded`
section.

The `embed_config` parameter in `add_endpoint` accepts an
`Lutaml::Hal::EndpointConfiguration` object that defines how embed requests
should be handled for that endpoint.

=== Embed mechanisms

==== General

The framework supports four different embed mechanisms:

* Parameter-based embed (most common)
* URL-based embed
* Header-based embed
* Auto embed

==== Parameter-based embed

This mechanism adds query parameters to the request URL to enable embed
functionality.

[example]
====
[source,ruby]
----
embed_config = Lutaml::Hal::EndpointConfiguration.new(
  mechanism: :parameter,
  parameter_name: 'embed',
  parameter_value: 'true'
)

register.add_endpoint(
  id: :product_index,
  type: :index,
  url: '/products',
  model: ProductIndex,
  embed_config: embed_config
)

# When fetching with embed enabled:
# GET /products?embed=true
----
====

==== URL-based embed

This mechanism uses special embed URLs that are different from the standard
resource URLs.

[example]
====
[source,ruby]
----
embed_config = Lutaml::Hal::EndpointConfiguration.new(
  mechanism: :url,
  embed_url: '/products/embedded'
)

register.add_endpoint(
  id: :product_index,
  type: :index,
  url: '/products',
  model: ProductIndex,
  embed_config: embed_config
)

# When fetching with embed enabled:
# GET /products/embedded
----
====

==== Header-based embed

This mechanism uses HTTP headers to request embedded content.

[example]
====
[source,ruby]
----
embed_config = Lutaml::Hal::EndpointConfiguration.new(
  mechanism: :header,
  header_name: 'X-Embed',
  header_value: 'true'
)

register.add_endpoint(
  id: :product_index,
  type: :index,
  url: '/products',
  model: ProductIndex,
  embed_config: embed_config
)

# When fetching with embed enabled:
# GET /products
# X-Embed: true
----
====

==== Auto embed

This mechanism assumes the server always provides embedded content without
any special configuration.

[example]
====
[source,ruby]
----
embed_config = Lutaml::Hal::EndpointConfiguration.new(
  mechanism: :auto
)

register.add_endpoint(
  id: :product_index,
  type: :index,
  url: '/products',
  model: ProductIndex,
  embed_config: embed_config
)

# All requests automatically include embedded content:
# GET /products
----
====

=== Working with embedded content

==== Checking for embedded content

Resources that support embed functionality provide methods to check for and
access embedded content:

[example]
====
[source,ruby]
----
# Fetch a resource with embed enabled
products = register.fetch(:product_index, embed: true)

# Check if embedded content exists
if products.has_embedded?('products')
  puts "Embedded products available"
end

# Get embedded content keys
embedded_keys = products.embedded_keys
puts "Available embedded content: #{embedded_keys}"

# Access embedded content directly
embedded_products = products.get_embedded('products')
----
====

==== Link realization with embedded content

When embedded content is available, link realization automatically uses the
embedded data instead of making additional HTTP requests:

[example]
====
[source,ruby]
----
# Fetch products with embedded content
products = register.fetch(:product_index, embed: true)

# Get the first product link
first_product_link = products.links.products.first

# Realize the link - uses embedded data if available
product = first_product_link.realize(parent_resource: products)
# No HTTP request made if embedded data exists!
----
====

=== Performance benefits

==== General

Using embed functionality can significantly improve performance by reducing
the number of HTTP requests:

[example]
====
[source,ruby]
----
# Without embed: Multiple HTTP requests
products_index = register.fetch(:product_index)  # 1 request
first_product = products_index.links.products.first.realize  # 2nd request
second_product = products_index.links.products[1].realize    # 3rd request
# Total: 3 HTTP requests

# With embed: Single HTTP request
products_index = register.fetch(:product_index, embed: true)  # 1 request
first_product = products_index.links.products.first.realize(
  parent_resource: products_index
)  # No additional request - uses embedded data
second_product = products_index.links.products[1].realize(
  parent_resource: products_index
)  # No additional request - uses embedded data
# Total: 1 HTTP request
----
====

=== Configuration examples

==== W3C API style configuration

[example]
====
[source,ruby]
----
# Configure multiple endpoints with parameter-based embed
%i[specification_index group_index series_index].each do |endpoint_id|
  register.add_endpoint(
    id: endpoint_id,
    type: :index,
    url: "/#{endpoint_id.to_s.gsub('_', 's')}",
    model: "#{endpoint_id.to_s.classify}".constantize,
    embed_config: Lutaml::Hal::EndpointConfiguration.new(
      mechanism: :parameter,
      parameter_name: 'embed',
      parameter_value: 'true'
    )
  )
end
----
====

==== Mixed mechanism configuration

[example]
====
[source,ruby]
----
# Different endpoints can use different embed mechanisms
register.add_endpoint(
  id: :product_index,
  type: :index,
  url: '/products',
  model: ProductIndex,
  embed_config: Lutaml::Hal::EndpointConfiguration.new(
    mechanism: :parameter,
    parameter_name: 'embed',
    parameter_value: 'true'
  )
)

register.add_endpoint(
  id: :category_index,
  type: :index,
  url: '/categories',
  model: CategoryIndex,
  embed_config: Lutaml::Hal::EndpointConfiguration.new(
    mechanism: :header,
    header_name: 'X-Include-Embedded',
    header_value: 'categories'
  )
)
----
====

== Next steps

=== General

Now that you understand how to define HAL resources and set up model
registers, you're ready to learn about using these definitions at runtime:

* link:runtime-usage-guide.adoc[Runtime usage guide] - Fetching resources,
  navigating links, and handling pagination
* link:hal-links-reference.adoc[HAL links reference] - Advanced link
  configuration and customization
* link:pagination-guide.adoc[Pagination guide] - Comprehensive pagination
  patterns and navigation
